<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Livre extends \App\Entity\Livre implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'auteurs' => [parent::class, 'auteurs', null, 16],
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'datePublication' => [parent::class, 'datePublication', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'editeur' => [parent::class, 'editeur', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageCouverture' => [parent::class, 'imageCouverture', null, 16],
        "\0".parent::class."\0".'isbn' => [parent::class, 'isbn', null, 16],
        "\0".parent::class."\0".'ligneCommandes' => [parent::class, 'ligneCommandes', null, 16],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null, 16],
        "\0".parent::class."\0".'stock' => [parent::class, 'stock', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        'auteurs' => [parent::class, 'auteurs', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'datePublication' => [parent::class, 'datePublication', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'editeur' => [parent::class, 'editeur', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageCouverture' => [parent::class, 'imageCouverture', null, 16],
        'isbn' => [parent::class, 'isbn', null, 16],
        'ligneCommandes' => [parent::class, 'ligneCommandes', null, 16],
        'prix' => [parent::class, 'prix', null, 16],
        'stock' => [parent::class, 'stock', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
