<?php

namespace ContainerWb5IL2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartControllervalidateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XVZadFo.App\Controller\CartController::validate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartService' => ['privates', 'App\\Service\\CartService', 'getCartServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cartService' => 'App\\Service\\CartService',
            'em' => '?',
        ]))->withContext('App\\Controller\\CartController::validate()', $container);

        if (isset($container->privates['.service_locator.XVZadFo.App\\Controller\\CartController::validate()'])) {
            return $container->privates['.service_locator.XVZadFo.App\\Controller\\CartController::validate()'];
        }

        return $container->privates['.service_locator.XVZadFo.App\\Controller\\CartController::validate()'] = $instance;
    }
}
