<?php

namespace ContainerWb5IL2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0Q_nXe_.App\Entity\Commande' shared service.
     *
     * @return \App\Entity\Commande
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0Q_nXe_": it needs an instance of "App\\Entity\\Commande" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
