<?php

namespace ContainerWb5IL2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c9GzW8B.App\Controller\LivreController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c9GzW8B.App\\Controller\\LivreController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livreRepository' => ['privates', 'App\\Repository\\LivreRepository', 'getLivreRepositoryService', true],
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'editeurRepository' => ['privates', 'App\\Repository\\EditeurRepository', 'getEditeurRepositoryService', true],
        ], [
            'livreRepository' => 'App\\Repository\\LivreRepository',
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'editeurRepository' => 'App\\Repository\\EditeurRepository',
        ]))->withContext('App\\Controller\\LivreController::index()', $container);
    }
}
