<?php

namespace ContainerWb5IL2t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3FWkHlB.App\Controller\ProfileController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.3FWkHlB'] ?? $container->load('get_ServiceLocator_3FWkHlBService'));

        if (isset($container->privates['.service_locator.3FWkHlB.App\\Controller\\ProfileController::index()'])) {
            return $container->privates['.service_locator.3FWkHlB.App\\Controller\\ProfileController::index()'];
        }

        $instance = $a->withContext('App\\Controller\\ProfileController::index()', $container);

        if (isset($container->privates['.service_locator.3FWkHlB.App\\Controller\\ProfileController::index()'])) {
            return $container->privates['.service_locator.3FWkHlB.App\\Controller\\ProfileController::index()'];
        }

        return $container->privates['.service_locator.3FWkHlB.App\\Controller\\ProfileController::index()'] = $instance;
    }
}
