<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWb5IL2t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWb5IL2t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWb5IL2t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWb5IL2t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWb5IL2t\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wb5IL2t',
    'container.build_id' => '7dc61d9a',
    'container.build_time' => 1767918010,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWb5IL2t');
